Modify webserver setup and startup

diff --git a/bootfs/etc/sysconfig/libexec/modules/service/service_system_modify_conf b/bootfs/etc/sysconfig/libexec/modules/service/service_system_modify_conf
--- a/bootfs/etc/sysconfig/libexec/modules/service/service_system_modify_conf
+++ b/bootfs/etc/sysconfig/libexec/modules/service/service_system_modify_conf
@@ -51,8 +51,27 @@ service_smb_start
 # Modify New Admin Password
 new_password=`echo ${QUERY_STRING} | cut '-d&' -f4`
 [ "$new_password" != "NaN" ] && {
- echo "admin:${new_password}" > /etc/sysconfig/config/webmaster.conf
+ WEBMASTER="/etc/sysconfig/config/webmaster.conf"
+ HTTP_CONF="/etc/sysconfig/config/httpd.conf"
+ echo "admin:${new_password}" > ${WEBMASTER}
  echo "admin:${new_password}" | /bin/chpasswd
  (echo "${new_password}";echo "${new_password}")|${SMB_PASSWD_PROG} -s -a admin >/dev/null 2>&1
+
+
+	# restart httpd for change password
+	/bin/killall httpd
+	PID=`/bin/pidof httpd`
+	for i in $PID; do
+	/bin/kill -9 $i >/dev/null 2>&1
+	done
+	/bin/logger "$0 - httpd deamon Stop"
+
+	creds=`/bin/cat ${WEBMASTER}`
+	echo "/:$creds" > ${HTTP_CONF}
+	/bin/nice -n -18 /sbin/httpd -h /var/www
+	[ $? -eq 0 ] &&\
+	/bin/logger "$0 - httpd deamon with BasicAuth Start Succeed" ||\
+	/bin/logger "$0 - httpd deamon with BasicAuth Start Failed"
+
  }
 }
